version: '3'

volumes:
  db-data:
    external: false
#  esdate:


services:
  db:
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    image: postgres:9.5
    volumes:
      - db-data:/usr/local/pgsql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data #user elasticsearch need access to read and write to folder
    ports:
      - 9200:9200

  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3002:3000"
    depends_on:
      - db
      - elasticsearch
    links:
      - db
      - elasticsearch
    environment:
      DB_USER: username
      DB_PASSWORD: password
      DB_HOST: db
      ELASTICSEARCH_HOST: elasticsearch